//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1008
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobRepo.SalarySurveyRef {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SalarySurvey", Namespace="http://schemas.datacontract.org/2004/07/JobRepoServices")]
    [System.SerializableAttribute()]
    public partial class SalarySurvey : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AverageSalaryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MaxSalaryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MinSalaryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RoleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AverageSalary {
            get {
                return this.AverageSalaryField;
            }
            set {
                if ((object.ReferenceEquals(this.AverageSalaryField, value) != true)) {
                    this.AverageSalaryField = value;
                    this.RaisePropertyChanged("AverageSalary");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MaxSalary {
            get {
                return this.MaxSalaryField;
            }
            set {
                if ((object.ReferenceEquals(this.MaxSalaryField, value) != true)) {
                    this.MaxSalaryField = value;
                    this.RaisePropertyChanged("MaxSalary");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MinSalary {
            get {
                return this.MinSalaryField;
            }
            set {
                if ((object.ReferenceEquals(this.MinSalaryField, value) != true)) {
                    this.MinSalaryField = value;
                    this.RaisePropertyChanged("MinSalary");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Role {
            get {
                return this.RoleField;
            }
            set {
                if ((object.ReferenceEquals(this.RoleField, value) != true)) {
                    this.RoleField = value;
                    this.RaisePropertyChanged("Role");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SalarySurveyRef.ISalarySurveyService")]
    public interface ISalarySurveyService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISalarySurveyService/GetAllRoles", ReplyAction="http://tempuri.org/ISalarySurveyService/GetAllRolesResponse")]
        JobRepo.SalarySurveyRef.SalarySurvey[] GetAllRoles();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISalarySurveyService/GetRole", ReplyAction="http://tempuri.org/ISalarySurveyService/GetRoleResponse")]
        JobRepo.SalarySurveyRef.SalarySurvey[] GetRole(string role);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISalarySurveyServiceChannel : JobRepo.SalarySurveyRef.ISalarySurveyService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SalarySurveyServiceClient : System.ServiceModel.ClientBase<JobRepo.SalarySurveyRef.ISalarySurveyService>, JobRepo.SalarySurveyRef.ISalarySurveyService {
        
        public SalarySurveyServiceClient() {
        }
        
        public SalarySurveyServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SalarySurveyServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SalarySurveyServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SalarySurveyServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public JobRepo.SalarySurveyRef.SalarySurvey[] GetAllRoles() {
            return base.Channel.GetAllRoles();
        }
        
        public JobRepo.SalarySurveyRef.SalarySurvey[] GetRole(string role) {
            return base.Channel.GetRole(role);
        }
    }
}
